// Generated by gencpp from file localization/PoseWithWeightStamped.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_POSEWITHWEIGHTSTAMPED_H
#define LOCALIZATION_MESSAGE_POSEWITHWEIGHTSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <localization/PoseWithWeight.h>

namespace localization
{
template <class ContainerAllocator>
struct PoseWithWeightStamped_
{
  typedef PoseWithWeightStamped_<ContainerAllocator> Type;

  PoseWithWeightStamped_()
    : header()
    , pose()  {
    }
  PoseWithWeightStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::localization::PoseWithWeight_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::localization::PoseWithWeightStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization::PoseWithWeightStamped_<ContainerAllocator> const> ConstPtr;

}; // struct PoseWithWeightStamped_

typedef ::localization::PoseWithWeightStamped_<std::allocator<void> > PoseWithWeightStamped;

typedef boost::shared_ptr< ::localization::PoseWithWeightStamped > PoseWithWeightStampedPtr;
typedef boost::shared_ptr< ::localization::PoseWithWeightStamped const> PoseWithWeightStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization::PoseWithWeightStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization::PoseWithWeightStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::localization::PoseWithWeightStamped_<ContainerAllocator1> & lhs, const ::localization::PoseWithWeightStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::localization::PoseWithWeightStamped_<ContainerAllocator1> & lhs, const ::localization::PoseWithWeightStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::localization::PoseWithWeightStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::PoseWithWeightStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::PoseWithWeightStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::PoseWithWeightStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::PoseWithWeightStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::PoseWithWeightStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization::PoseWithWeightStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab09b0858359112f2e340cfe7b7e9803";
  }

  static const char* value(const ::localization::PoseWithWeightStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab09b0858359112fULL;
  static const uint64_t static_value2 = 0x2e340cfe7b7e9803ULL;
};

template<class ContainerAllocator>
struct DataType< ::localization::PoseWithWeightStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization/PoseWithWeightStamped";
  }

  static const char* value(const ::localization::PoseWithWeightStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization::PoseWithWeightStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This expresses an estimated pose with a reference coordinate frame and timestamp\n"
"\n"
"Header header\n"
"localization/PoseWithWeight pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: localization/PoseWithWeight\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"geometry_msgs/Pose pose\n"
"\n"
"# float weight\n"
"float32 weight\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::localization::PoseWithWeightStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization::PoseWithWeightStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseWithWeightStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization::PoseWithWeightStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization::PoseWithWeightStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::localization::PoseWithWeight_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MESSAGE_POSEWITHWEIGHTSTAMPED_H
