// Generated by gencpp from file localization/PoseWithWeight.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_POSEWITHWEIGHT_H
#define LOCALIZATION_MESSAGE_POSEWITHWEIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace localization
{
template <class ContainerAllocator>
struct PoseWithWeight_
{
  typedef PoseWithWeight_<ContainerAllocator> Type;

  PoseWithWeight_()
    : pose()
    , weight(0.0)  {
    }
  PoseWithWeight_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , weight(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _weight_type;
  _weight_type weight;





  typedef boost::shared_ptr< ::localization::PoseWithWeight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization::PoseWithWeight_<ContainerAllocator> const> ConstPtr;

}; // struct PoseWithWeight_

typedef ::localization::PoseWithWeight_<std::allocator<void> > PoseWithWeight;

typedef boost::shared_ptr< ::localization::PoseWithWeight > PoseWithWeightPtr;
typedef boost::shared_ptr< ::localization::PoseWithWeight const> PoseWithWeightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization::PoseWithWeight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization::PoseWithWeight_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::localization::PoseWithWeight_<ContainerAllocator1> & lhs, const ::localization::PoseWithWeight_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.weight == rhs.weight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::localization::PoseWithWeight_<ContainerAllocator1> & lhs, const ::localization::PoseWithWeight_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::localization::PoseWithWeight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::PoseWithWeight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::PoseWithWeight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::PoseWithWeight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::PoseWithWeight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::PoseWithWeight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization::PoseWithWeight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f95056f54b0dad30bf874936f8a81e13";
  }

  static const char* value(const ::localization::PoseWithWeight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf95056f54b0dad30ULL;
  static const uint64_t static_value2 = 0xbf874936f8a81e13ULL;
};

template<class ContainerAllocator>
struct DataType< ::localization::PoseWithWeight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization/PoseWithWeight";
  }

  static const char* value(const ::localization::PoseWithWeight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization::PoseWithWeight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents a pose in free space with uncertainty.\n"
"\n"
"geometry_msgs/Pose pose\n"
"\n"
"# float weight\n"
"float32 weight\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::localization::PoseWithWeight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization::PoseWithWeight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseWithWeight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization::PoseWithWeight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization::PoseWithWeight_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "weight: ";
    Printer<float>::stream(s, indent + "  ", v.weight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MESSAGE_POSEWITHWEIGHT_H
