// Generated by gencpp from file localization/SetInitialPoseResponse.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_SETINITIALPOSERESPONSE_H
#define LOCALIZATION_MESSAGE_SETINITIALPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace localization
{
template <class ContainerAllocator>
struct SetInitialPoseResponse_
{
  typedef SetInitialPoseResponse_<ContainerAllocator> Type;

  SetInitialPoseResponse_()
    {
    }
  SetInitialPoseResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::localization::SetInitialPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization::SetInitialPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetInitialPoseResponse_

typedef ::localization::SetInitialPoseResponse_<std::allocator<void> > SetInitialPoseResponse;

typedef boost::shared_ptr< ::localization::SetInitialPoseResponse > SetInitialPoseResponsePtr;
typedef boost::shared_ptr< ::localization::SetInitialPoseResponse const> SetInitialPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization::SetInitialPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization::SetInitialPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::localization::SetInitialPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::SetInitialPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::SetInitialPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::SetInitialPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::SetInitialPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::SetInitialPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization::SetInitialPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::localization::SetInitialPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::localization::SetInitialPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization/SetInitialPoseResponse";
  }

  static const char* value(const ::localization::SetInitialPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization::SetInitialPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::localization::SetInitialPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization::SetInitialPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInitialPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization::SetInitialPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::localization::SetInitialPoseResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MESSAGE_SETINITIALPOSERESPONSE_H
