// Generated by gencpp from file localization/SetInitialPose.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_SETINITIALPOSE_H
#define LOCALIZATION_MESSAGE_SETINITIALPOSE_H

#include <ros/service_traits.h>


#include <localization/SetInitialPoseRequest.h>
#include <localization/SetInitialPoseResponse.h>


namespace localization
{

struct SetInitialPose
{

typedef SetInitialPoseRequest Request;
typedef SetInitialPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInitialPose
} // namespace localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localization::SetInitialPose > {
  static const char* value()
  {
    return "2e51d06c4c070500696986776da1d81d";
  }

  static const char* value(const ::localization::SetInitialPose&) { return value(); }
};

template<>
struct DataType< ::localization::SetInitialPose > {
  static const char* value()
  {
    return "localization/SetInitialPose";
  }

  static const char* value(const ::localization::SetInitialPose&) { return value(); }
};


// service_traits::MD5Sum< ::localization::SetInitialPoseRequest> should match
// service_traits::MD5Sum< ::localization::SetInitialPose >
template<>
struct MD5Sum< ::localization::SetInitialPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localization::SetInitialPose >::value();
  }
  static const char* value(const ::localization::SetInitialPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization::SetInitialPoseRequest> should match
// service_traits::DataType< ::localization::SetInitialPose >
template<>
struct DataType< ::localization::SetInitialPoseRequest>
{
  static const char* value()
  {
    return DataType< ::localization::SetInitialPose >::value();
  }
  static const char* value(const ::localization::SetInitialPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localization::SetInitialPoseResponse> should match
// service_traits::MD5Sum< ::localization::SetInitialPose >
template<>
struct MD5Sum< ::localization::SetInitialPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localization::SetInitialPose >::value();
  }
  static const char* value(const ::localization::SetInitialPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization::SetInitialPoseResponse> should match
// service_traits::DataType< ::localization::SetInitialPose >
template<>
struct DataType< ::localization::SetInitialPoseResponse>
{
  static const char* value()
  {
    return DataType< ::localization::SetInitialPose >::value();
  }
  static const char* value(const ::localization::SetInitialPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZATION_MESSAGE_SETINITIALPOSE_H
