// Generated by gencpp from file rbo_create/ResetOdom.msg
// DO NOT EDIT!


#ifndef RBO_CREATE_MESSAGE_RESETODOM_H
#define RBO_CREATE_MESSAGE_RESETODOM_H

#include <ros/service_traits.h>


#include <rbo_create/ResetOdomRequest.h>
#include <rbo_create/ResetOdomResponse.h>


namespace rbo_create
{

struct ResetOdom
{

typedef ResetOdomRequest Request;
typedef ResetOdomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetOdom
} // namespace rbo_create


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbo_create::ResetOdom > {
  static const char* value()
  {
    return "d097c2ef742c9464ee3a0e656d7572a2";
  }

  static const char* value(const ::rbo_create::ResetOdom&) { return value(); }
};

template<>
struct DataType< ::rbo_create::ResetOdom > {
  static const char* value()
  {
    return "rbo_create/ResetOdom";
  }

  static const char* value(const ::rbo_create::ResetOdom&) { return value(); }
};


// service_traits::MD5Sum< ::rbo_create::ResetOdomRequest> should match
// service_traits::MD5Sum< ::rbo_create::ResetOdom >
template<>
struct MD5Sum< ::rbo_create::ResetOdomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbo_create::ResetOdom >::value();
  }
  static const char* value(const ::rbo_create::ResetOdomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbo_create::ResetOdomRequest> should match
// service_traits::DataType< ::rbo_create::ResetOdom >
template<>
struct DataType< ::rbo_create::ResetOdomRequest>
{
  static const char* value()
  {
    return DataType< ::rbo_create::ResetOdom >::value();
  }
  static const char* value(const ::rbo_create::ResetOdomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbo_create::ResetOdomResponse> should match
// service_traits::MD5Sum< ::rbo_create::ResetOdom >
template<>
struct MD5Sum< ::rbo_create::ResetOdomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbo_create::ResetOdom >::value();
  }
  static const char* value(const ::rbo_create::ResetOdomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbo_create::ResetOdomResponse> should match
// service_traits::DataType< ::rbo_create::ResetOdom >
template<>
struct DataType< ::rbo_create::ResetOdomResponse>
{
  static const char* value()
  {
    return DataType< ::rbo_create::ResetOdom >::value();
  }
  static const char* value(const ::rbo_create::ResetOdomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBO_CREATE_MESSAGE_RESETODOM_H
