(cl:defpackage localization-msg
  (:use )
  (:export
   "<POSEWITHWEIGHT>"
   "POSEWITHWEIGHT"
   "<POSEWITHWEIGHTARRAY>"
   "POSEWITHWEIGHTARRAY"
   "<POSEWITHWEIGHTSTAMPED>"
   "POSEWITHWEIGHTSTAMPED"
  ))

